### ISSUE TITLE
Setup equipment and garden

### ISSUE THREAD

**Issue by akagopher8** [rawrool/Group7_SmartGarden#68]
Setup the hardware for the garden and the irrigation and plant the plants.

**Comment by akagopher8** [comment]
I helped Christian set up the irrigation in our box and plant all of the plants in all 4 of the plots. Will need to check to ensure the arduino is working and watering properly so the plants do not die immediately.  2.5 hours spent helping

**Comment by rawrool** [comment]
I assisted in setting up the hardware. Which entailed having to connect the water lines and rewire the sensor, water valve, and the solar panel.
Spent: 1h:47m

I couldn't test the automated watering after setting it up because Jason had the water meter.  The next day after Jason and Christopher had set up the water meter and irrigation system I checked to see it the automated watering was working properly and found it was not. Therefore, I removed the board and it's components and took them home to troubleshoot. I found issues in the quality of the wires and in my code. While, I fixed some of the issues Arjun was in charge of doing manual watering so that the plants wouldn't die. After the weekend, I was able to resolve all the issues and the system was re-setup on Monday.
Spent: 8h
